name: 'Cache install Nix packages'
description: 'Use the GitHub Actions cache for Nix packages'
author: 'Rik Huijzer'
inputs:
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring the cache if no cache hit occurred for key'
    required: false
  nix_version:
    description: 'Nix version, defaults to `nixos-unstable`.'
    default: 'nixos-unstable'
  nix_file:
    description: 'Nix file of form `{ pkgs }: []`.'
    default: default.nix
  shell_file:
    description: 'Nix shell file, requires `mkShell { buildInputs }`.'
    default: shell.nix
  auto_optimise:
    description: 'Whether to run `nix-store --optimise` before caching.'
    default: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down'
  color: 'blue'
