name: "Cache install Nix packages"
description: Use the GitHub Actions cache for Nix packages
author: "Rik Huijzer"
inputs:
  key-prefix:
    description: |-
      The prefix to use for the evaluated cache key.
    default: nix-${{ runner.os }}-
    required: false
  nix-path:
    description: |-
      Nix path to use (e.g. `nixpkgs=channel:nixos-unstable`), defaults to
      <nixpkgs> being nixos-unstable. Prefer manually importing Nixpkgs whenever
      possible.
    default: nixpkgs=channel:nixos-unstable
  nix-file:
    description: |-
      Nix file of form `{ pkgs }: []`.
    default: default.nix
  shell-file:
    description: |-
      Nix shell file, requires `mkShell { buildInputs }`.
    default: shell.nix
  instantiated-files:
    description: |-
      Nix files to instantiate for the cache but not install.
    required: false
  instantiated-expression:
    description: |-
      Nix expression to instantiate for the cache but not install.
    required: false
  auto-optimise:
    description: |-
      Whether to run `nix-store --optimise` before caching.
    default: true
outputs:
  cache-hit:
    description: |-
      A boolean value to indicate an exact match was found for the primary key.
runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
branding:
  icon: "arrow-down"
  color: "blue"
