name: test-shell

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-save-simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shell
        uses: ./
        with:
          nix-path: nixpkgs=channel:nixos-unstable
          shell-file: shell.nix

      - name: Hello!
        run: hello
