name: test-shell

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shell
        uses: ./
        with:
          shell-file: test/shell.nix

      - name: Hello!
        run: hello
