name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-save-simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save cache
        uses: ./
        with:
          nix-file: "test/simple.nix"
          nix-path: nixpkgs=channel:nixos-unstable
          key-prefix: test-${{ github.run_id }}-

      - name: Test whether simple.nix is installed
        run: which hello

  test-restore-simple:
    needs: test-save-simple
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore cache
        uses: ./
        with:
          nix-file: "test/simple.nix"
          nix-path: nixpkgs=channel:nixos-unstable
          key-prefix: test-${{ github.run_id }}-
          instantiated-expression: |
            [
              (import ./test/simple.nix)
              (import <nixpkgs> {}).hello
            ]

      - name: Test whether simple.nix is installed
        run: hello

      - name: Test whether nix-shell is available
        run: nix-shell -p nix-info --run "nix-info -m"
